return {
		'loctvl842/monokai-pro.nvim',
		'folke/tokyonight.nvim',
		'mcchrish/zenbones.nvim',

		{'nyoom-engineering/oxocarbon.nvim', lazy = true},
		{'rebelot/kanagawa.nvim', lazy = true},
		{'AlexvZyl/nordic.nvim', lazy = true},
		{'savq/melange-nvim', lazy = true},
		{'shaunsingh/nord.nvim', lazy = true},
		{'andersevenrud/nordic.nvim', lazy = true},
		{'EdenEast/nightfox.nvim', lazy = true},
		{'olivercederborg/poimandres.nvim', lazy = true},
		{'ribru17/bamboo.nvim', lazy = true},
		{'rose-pine/neovim', lazy = true},

		"sainnhe/sonokai",
		'sainnhe/everforest',
		'mhartington/oceanic-next',
		'soft-aesthetic/soft-era-vim',
		'chuling/ci_dark',
		'askfiy/visual_studio_code',
		'Mofiqul/vscode.nvim',
		'romainl/Apprentice',
		-- 'arzg/vim-colors-xcode',
		'wuelnerdotexe/vim-enfocado',
		'kaicataldo/material.vim',
		'cocopon/iceberg.vim',
		'rafi/awesome-vim-colorschemes',
		'skywind3000/vim-colorschemes',
		'jaredgorski/SpaceCamp',
		'mswift42/vim-themes',
}


